### ISSUE TITLE
Clear inputs after registration completed

### ISSUE THREAD

**Issue by adliano** [adliano/thepetinder_react#37]
# Clear the texts inputs after registration it's completed
The idea its to clear all text inputs like:
  - name
  - email
  - password
  - etc
After user successful register.
After results.error as well.
Need to validate form if no inputs are there so that error of undefined not thrown.

**Comment by josemenis** [comment]
So far clears input for successful registration, that's been merged.
Still need to validate form so no errors are thrown when inputs are empty and button is pressed.
Also clear inputs when results.error
